package `in`.tatkalfast.assistant.ui

class Words(val tamil: Boolean) {
 fun t(key: String): String = values[key]?.let { if(tamil) it.second else it.first } ?: key
 companion object { private val values = mapOf(
  "backup_title" to ("Encrypted backup / restore" to "மறையாக்கக் காப்பு / மீட்டெடுப்பு"),
  "backup_note" to ("Save profiles and booking records before changing phones or reinstalling. Use a unique passphrase of 12–128 characters. Keep the file and passphrase safe: we cannot recover a forgotten passphrase. Backups contain personal details; only share intentionally. Settings and reminders are not included." to "சாதனத்தை மாற்றும் அல்லது மீண்டும் நிறுவும் முன் விவரங்களைக் காப்பெடுக்கவும். 12–128 எழுத்துள்ள தனிப்பட்ட கடவுச்சொற்றொடரைப் பயன்படுத்தவும். கோப்பையும் கடவுச்சொற்றொடரையும் பாதுகாக்கவும். மறந்த கடவுச்சொற்றொடரை மீட்க முடியாது. அமைப்புகள் மற்றும் நினைவூட்டல்கள் இதில் இல்லை."),
  "backup_password_label" to ("Backup passphrase (12+ characters)" to "காப்புக் கடவுச்சொற்றொடர் (12+ எழுத்துகள்)"),
  "backup_repeat" to ("Repeat passphrase" to "கடவுச்சொற்றொடரை மீண்டும் உள்ளிடு"),
  "backup_export" to ("Choose file and export" to "கோப்பைத் தேர்ந்து காப்பெடு"),
  "backup_import" to ("Choose encrypted backup" to "மறையாக்கக் காப்பைத் தேர்வு செய்"),
  "backup_decrypt" to ("Unlock backup and preview" to "காப்பைத் திறந்து முன்னோட்டம் காண்"),
  "backup_restore" to ("Confirm merge" to "இணைப்பை உறுதிசெய்"),
  "backup_merge_note" to ("Existing profile IDs are kept. Imported unresolved bookings remain locked until checked. A restore never clears a pending-payment lock." to "தற்போதைய விவரங்கள் பாதுகாக்கப்படும். தீர்க்கப்படாத முன்பதிவு முயற்சிகளின் பூட்டு தொடரும். நிலுவைக் கட்டணப் பூட்டை மீட்டெடுப்பு நீக்காது."),
  "backup_saved" to ("Encrypted backup saved. Keep its passphrase separately." to "மறையாக்கக் காப்பு சேமிக்கப்பட்டது. கடவுச்சொற்றொடரைத் தனியாக வைக்கவும்."),
  "backup_restored" to ("Backup merged successfully. Review profiles and any unresolved booking before starting." to "காப்பு இணைக்கப்பட்டது. தொடங்கும் முன் விவரங்களையும் தீர்க்கப்படாத முயற்சியையும் சரிபார்க்கவும்."),
  "backup_enter_password" to ("Backup selected. Unlock this screen and enter its passphrase." to "காப்பு தேர்ந்தெடுக்கப்பட்டது. திரையைத் திறந்து கடவுச்சொற்றொடரை உள்ளிடவும்."),
  "backup_invalid" to ("Cannot open or merge this backup. Check the passphrase, file integrity and supported version. No local data was replaced." to "காப்பைத் திறக்க அல்லது இணைக்க முடியவில்லை. கடவுச்சொற்றொடர் மற்றும் கோப்பைச் சரிபார்க்கவும். உள்ளூர் தரவு மாற்றப்படவில்லை."),
  "backup_io" to ("Could not finish the file operation. Keep the app open and retry; a partial export file must not be used." to "கோப்புச் செயல் முடியவில்லை. செயலியைத் திறந்துவைத்து மீண்டும் முயலவும். முழுமையற்ற காப்பைப் பயன்படுத்த வேண்டாம்."),
  "backup_active_conflict" to ("The backup and this phone contain different unresolved attempts. Verify and resolve the existing attempt before importing. Nothing was changed." to "காப்பிலும் சாதனத்திலும் வெவ்வேறு தீர்க்கப்படாத முயற்சிகள் உள்ளன. தற்போதைய முயற்சியைச் சரிபார்த்து முடித்த பின் மீண்டும் முயலவும். எதுவும் மாற்றப்படவில்லை."),
  "journeys_count" to ("Journeys" to "பயணங்கள்"),
  "confirmation_note" to ("Optional: paste your official confirmation text to extract its PNR. This does not verify a booking or payment. Review the journey and both official records below." to "விருப்பம்: அதிகாரப்பூர்வ உறுதிப்படுத்தல் உரையை ஒட்டி PNR எண்ணைப் பெறவும். இது முன்பதிவு அல்லது கட்டணச் சரிபார்ப்பு அல்ல."),
  "confirmation_paste" to ("Paste confirmation text" to "உறுதிப்படுத்தல் உரையை ஒட்டு"),
  "confirmation_extract" to ("Use labelled PNR" to "PNR எண்ணைப் பயன்படுத்து"),
  "confirmation_invalid" to ("No single labelled 10-digit PNR found. Enter it manually." to "தனித்த 10 இலக்க PNR கிடைக்கவில்லை. கைமுறையாக உள்ளிடவும்."),
  "readiness" to ("Booking setup check" to "முன்பதிவு அமைப்புச் சரிபார்ப்பு"),
  "ready_android" to ("Android 9+ web autofill" to "Android 9+ இணையத் தானியங்கு நிரப்பல்"),
  "ready_chrome" to ("Verified Google Chrome installed" to "சரிபார்க்கப்பட்ட Google Chrome நிறுவப்பட்டுள்ளது"),
  "ready_provider" to ("This app selected for Android autofill" to "Android தானியங்கு நிரப்பலுக்கு இச்செயலி தேர்வு"),
  "ready_lock" to ("Device screen lock configured" to "சாதனத் திரைப் பூட்டு அமைப்பு"),
  "ready_clock" to ("Automatic device time enabled" to "தானியங்கு நேர அமைப்பு"),
  "ready_notifications" to ("Notifications allowed" to "அறிவிப்புகள் அனுமதி"),
  "ready_yes" to ("Ready" to "தயார்"),
  "ready_action" to ("Check settings" to "அமைப்புகளைச் சரிபார்"),
  "ready_note" to ("Checks update when you return. Also enable another autofill provider in Chrome settings. These checks do not test IRCTC fields, server time, availability or payment status. Notifications remain approximate." to "திரும்பும்போது சரிபார்ப்புகள் புதுப்பிக்கப்படும். Chrome அமைப்பிலும் மற்ற நிரப்பல் வழங்குநரை இயக்கவும். இது IRCTC புலங்கள், நேரம், இருக்கை அல்லது கட்டண நிலையைச் சரிபார்க்காது."),

  "autofill_title" to ("Prepared-detail autofill" to "தயாரித்த விவரங்களைத் தானாக நிரப்பு"),
  "autofill_enable" to ("Set up Android autofill" to "Android தானியங்கு நிரப்பலை அமை"),
  "autofill_setup_note" to ("Optional: select Tatkal Fast Assistant as your Android autofill provider, then choose another provider in Chrome’s Autofill services setting. Android permits one active provider, so this replaces your current provider. Supports recognized fields on HTTPS IRCTC pages in verified Google Chrome on Android 9+. Unlock and review recognized sibling fields together. Custom station selectors and unsupported fields still need manual entry." to "விருப்பம்: Android தானியங்கு நிரப்பல் வழங்குநராக தட்கல் உதவியாளரைத் தேர்ந்து, Chrome Autofill services அமைப்பில் மற்ற வழங்குநரைத் தேர்வு செய்யவும். Android-இல் ஒரு வழங்குநர் மட்டுமே செயல்படுவார்; தற்போதைய வழங்குநர் மாற்றப்படுவார். Android 9+ இல் சரிபார்த்த Chrome-இன் HTTPS IRCTC பக்கங்களில் அறியப்பட்ட புலங்களுக்கு ஆதரவு. அறியப்பட்ட இணைப் புலங்களை ஒன்றாகச் சரிபார்க்கவும். ஆதரவில்லாத புலங்களை கைமுறையாக நிரப்பவும்."),
  "autofill_review" to ("Review autofill detail" to "நிரப்பப்படும் விவரத்தைச் சரிபார்"),
  "autofill_review_note" to ("Only the listed fields will be filled. Check the selected passenger and every value; existing values in those fields may be replaced. Select the matching station suggestion yourself. Nothing is submitted." to "பட்டியலிட்ட புலங்கள் நிரப்பப்படும். பயணி மற்றும் ஒவ்வொரு மதிப்பையும் சரிபார்க்கவும்; பழைய மதிப்புகள் மாற்றப்படலாம். சரியான நிலையப் பரிந்துரையை நீங்களே தேர்வு செய்யவும். எதுவும் சமர்ப்பிக்கப்படாது."),
  "autofill_fill" to ("Fill reviewed fields" to "சரிபார்த்த புலங்களை நிரப்பு"),
  "autofill_no_attempt" to ("No eligible active attempt. Start a reviewed journey in the assistant first. Payment-pending and unknown attempts cannot autofill." to "தகுதியான செயலில் உள்ள முயற்சி இல்லை. முதலில் உதவியாளரில் சரிபார்த்த பயணத்தைத் தொடங்கவும். கட்டணம் நிலுவை அல்லது தெரியாத நிலையில் நிரப்ப முடியாது."),
  "autofill_unavailable" to ("Autofill settings are unavailable on this device. Use prepared-field copying." to "இந்தச் சாதனத்தில் தானியங்கு நிரப்பல் அமைப்பு கிடைக்கவில்லை. விவரங்களை நகலெடுத்துப் பயன்படுத்தவும்."),
  "PASSENGER_NAME" to ("Passenger name" to "பயணியின் பெயர்"),
  "PASSENGER_AGE" to ("Passenger age" to "பயணியின் வயது"),
  "MOBILE" to ("Mobile number" to "கைப்பேசி எண்"),
  "FROM" to ("From station" to "புறப்படும் நிலையம்"),
  "TO" to ("To station" to "சேரும் நிலையம்"),
  "BOARDING" to ("Boarding station" to "ஏறும் நிலையம்"),
  "TRAIN" to ("Train number" to "ரயில் எண்"),
  "payment_check" to ("Verified payment outcome" to "சரிபார்த்த கட்டண முடிவு"),
  "history_checked" to ("I checked official IRCTC booking history for this attempt." to "இந்த முயற்சிக்கான அதிகாரப்பூர்வ IRCTC முன்பதிவு வரலாற்றைச் சரிபார்த்தேன்."),
  "payment_checked" to ("I checked the bank, UPI or eWallet transaction status." to "வங்கி, UPI அல்லது இ-வாலட் பரிவர்த்தனை நிலையைச் சரிபார்த்தேன்."),
  "NOT_STARTED" to ("Payment was not started" to "கட்டணம் தொடங்கப்படவில்லை"),
  "FAILED_PAYMENT" to ("Payment failed; no debit pending" to "கட்டணம் தோல்வி; பற்று நிலுவை இல்லை"),
  "REFUNDED" to ("Refund confirmed" to "பணம் திரும்பியது உறுதி"),
  "PAID" to ("Payment completed" to "கட்டணம் முடிந்தது"),
  "PENDING_CHECK" to ("Payment pending" to "கட்டணம் நிலுவை"),
  "UNKNOWN_CHECK" to ("Payment status unknown" to "கட்டண நிலை தெரியவில்லை"),
  "recent_booking" to ("Recent booking" to "சமீபத்திய முன்பதிவு"),
  "home" to ("Home" to "முகப்பு"),
  "bookings" to ("Bookings" to "முன்பதிவுகள்"),
  "passengers" to ("Passengers" to "பயணிகள்"),
  "profile" to ("Profile" to "அமைப்புகள்"),
  "brand" to ("Tatkal Fast" to "தட்கல் விரைவு"),
  "tagline" to ("Prepare calmly. Book with confidence." to "தயாராகுங்கள். நம்பிக்கையுடன் முன்பதிவு செய்யுங்கள்."),
  "add_journey" to ("New journey" to "புதிய பயணம்"),
  "edit" to ("Edit" to "திருத்து"),
  "save" to ("Save" to "சேமி"),
  "cancel" to ("Cancel" to "விலகு"),
  "delete" to ("Delete" to "நீக்கு"),
  "start" to ("Review & start booking" to "சரிபார்த்து முன்பதிவைத் தொடங்கு"),
  "official" to ("Open official IRCTC" to "அதிகாரப்பூர்வ IRCTC திற"),
  "check_train" to ("Check train on IRCTC" to "IRCTC-இல் ரயிலைச் சரிபார்"),
  "payment_settings" to ("Payment preference" to "கட்டண விருப்பம்"),
  "empty_journey" to ("Prepare your first journey" to "முதல் பயணத்தைத் தயார்செய்"),
  "empty_hint" to ("Add passengers, then save a journey. Your information stays on this device." to "பயணிகளைச் சேர்த்து பயணத்தைச் சேமிக்கவும். விவரங்கள் இந்தச் சாதனத்தில் இருக்கும்."),
  "countdown" to ("TATKAL OPENS IN" to "தட்கல் முன்பதிவு தொடங்க"),
  "opened" to ("Scheduled opening time has passed. Check availability on IRCTC." to "திட்டமிட்ட தொடக்க நேரம் கடந்துவிட்டது. IRCTC-இல் இடவசதியைச் சரிபார்க்கவும்."),
  "no_countdown" to ("No Tatkal countdown for this class/quota." to "இந்த வகுப்பு/ஒதுக்கீட்டிற்கு தட்கல் நேரக் கணிப்பு இல்லை."),
  "clock_note" to ("IST • Uses the train origin departure date and your device clock. Availability is confirmed only by IRCTC." to "இந்திய நேரம் • ரயில் புறப்படும் முதல் நிலையத் தேதி மற்றும் சாதனக் கடிகாரம் அடிப்படை. IRCTC மட்டுமே இடவசதியை உறுதிப்படுத்தும்."),
  "remind" to ("Remind me 2 minutes before" to "2 நிமிடங்களுக்கு முன் நினைவூட்டு"),
  "reminder_set" to ("Reminder scheduled. Android may delay delivery; keep the app open near booking time." to "நினைவூட்டல் அமைக்கப்பட்டது. Android தாமதப்படுத்தலாம்; முன்பதிவு நேரத்தில் செயலியைத் திறந்து வைக்கவும்."),
  "reminder_denied" to ("Allow notifications in Android settings to receive reminders." to "நினைவூட்டலுக்கு Android அமைப்புகளில் அறிவிப்புகளை அனுமதிக்கவும்."),
  "journey_name" to ("Profile name" to "பயணப் பெயர்"),
  "from" to ("From station code" to "புறப்படும் நிலையக் குறியீடு"),
  "to" to ("To station code" to "சேரும் நிலையக் குறியீடு"),
  "date" to ("Boarding date • YYYY-MM-DD" to "ஏறும் தேதி • YYYY-MM-DD"),
  "origin_date" to ("Train origin departure date • YYYY-MM-DD" to "முதல் நிலையப் புறப்பாட்டுத் தேதி • YYYY-MM-DD"),
  "origin_help" to ("For overnight trains, the origin date may be earlier than your boarding date. Verify the timetable." to "இரவு ரயில்களுக்கு முதல் நிலையப் புறப்பாட்டுத் தேதி ஏறும் தேதிக்கு முந்தையதாக இருக்கலாம். கால அட்டவணையைச் சரிபார்க்கவும்."),
  "boarding" to ("Boarding station code" to "ஏறும் நிலையக் குறியீடு"),
  "train" to ("Train number • 5 digits" to "ரயில் எண் • 5 இலக்கங்கள்"),
  "class" to ("Class" to "வகுப்பு"),
  "quota" to ("Quota" to "ஒதுக்கீடு"),
  "berth" to ("Berth preference" to "படுக்கை விருப்பம்"),
  "meal" to ("Meal preference" to "உணவு விருப்பம்"),
  "mobile" to ("Indian mobile number" to "இந்திய கைப்பேசி எண்"),
  "name" to ("Passenger name" to "பயணியின் பெயர்"),
  "age" to ("Age on journey date" to "பயணத் தேதியில் வயது"),
  "gender" to ("Gender" to "பாலினம்"),
  "nationality" to ("Nationality • ISO code, e.g. IN" to "குடியுரிமை • ISO குறியீடு, எ.கா. IN"),
  "group" to ("Group • Family, Parents, Friends, Work" to "குழு • குடும்பம், பெற்றோர், நண்பர்கள், வேலை"),
  "senior" to ("Senior preference (only if offered by IRCTC)" to "மூத்த குடிமக்கள் விருப்பம் (IRCTC வழங்கினால் மட்டும்)"),
  "child" to ("Child berth required (under 12)" to "குழந்தைக்குப் படுக்கை தேவை (12 வயதிற்குக் கீழ்)"),
  "add_passenger" to ("Add passenger" to "பயணியைச் சேர்"),
  "select_group" to ("Select this group" to "இந்தக் குழுவைத் தேர்வு செய்"),
  "no_passengers" to ("No saved passengers yet." to "பயணிகள் இன்னும் சேமிக்கப்படவில்லை."),
  "no_history" to ("No booking records yet." to "முன்பதிவுப் பதிவுகள் இல்லை."),
  "upcoming" to ("Upcoming" to "வரவிருக்கும்"),
  "completed" to ("Completed" to "முடிந்தவை"),
  "cancelled" to ("Cancelled" to "ரத்தானவை"),
  "attempts" to ("Other attempts" to "மற்ற முயற்சிகள்"),
  "user_record" to ("Recorded by you • not independently verified" to "உங்களால் பதிவு செய்யப்பட்டது • தனியாகச் சரிபார்க்கப்படவில்லை"),
  "review_title" to ("Verify prepared details" to "தயாரித்த விவரங்களைச் சரிபார்"),
  "review_check" to ("I have checked the journey and passenger details." to "பயணம் மற்றும் பயணிகளின் விவரங்களைச் சரிபார்த்தேன்."),
  "handoff_note" to ("IRCTC opens in your browser. Use saved details below or IRCTC’s own Master List. Enter CAPTCHA, OTP and payment authorization only on the official flow." to "IRCTC உங்கள் உலாவியில் திறக்கும். கீழுள்ள விவரங்கள் அல்லது IRCTC Master List பயன்படுத்தவும். CAPTCHA, OTP மற்றும் கட்டண அனுமதியை அதிகாரப்பூர்வத் தளத்தில் மட்டும் உள்ளிடவும்."),
  "identity_note" to ("Complete IRCTC Aadhaar authentication in advance. Tatkal may require Aadhaar OTP. This app never collects Aadhaar or OTP." to "IRCTC ஆதார் சரிபார்ப்பை முன்கூட்டியே முடிக்கவும். தட்கலுக்கு ஆதார் OTP தேவைப்படலாம். இச்செயலி ஆதார் அல்லது OTP பெறாது."),
  "active" to ("Booking in progress" to "முன்பதிவு நடைபெறுகிறது"),
  "local_stage" to ("Your checklist stage" to "உங்கள் சரிபார்ப்புப் படிநிலை"),
  "lock_note" to ("A booking attempt is unresolved. New attempts are locked. This app cannot see the browser or check payment status. Verify IRCTC booking history and your payment provider before resolving." to "ஒரு முன்பதிவு முயற்சி முடிவறியாமல் உள்ளது. புதிய முயற்சிகள் முடக்கப்பட்டுள்ளன. இச்செயலியால் உலாவி அல்லது கட்டண நிலையைப் பார்க்க முடியாது. IRCTC வரலாறு மற்றும் கட்டண நிலையைச் சரிபார்க்கவும்."),
  "next_stage" to ("I completed this step" to "இந்தப் படிநிலையை முடித்தேன்"),
  "session_expired" to ("Session expired" to "அமர்வு காலாவதியானது"),
  "uncertain" to ("Network issue / status uncertain" to "இணையச் சிக்கல் / நிலை உறுதியில்லை"),
  "captcha_note" to ("Enter CAPTCHA or OTP yourself on IRCTC. Return here only if you need prepared details." to "CAPTCHA அல்லது OTP-ஐ IRCTC-இல் நீங்களே உள்ளிடவும். தயாரித்த விவரங்கள் தேவைப்பட்டால் இங்கு வரவும்."),
  "pending_note" to ("Do not pay again. Check official booking history and payment status first." to "மீண்டும் பணம் செலுத்தாதீர்கள். முதலில் அதிகாரப்பூர்வ முன்பதிவு வரலாறு மற்றும் கட்டண நிலையைச் சரிபார்க்கவும்."),
  "resolve" to ("Record verified outcome" to "சரிபார்த்த முடிவைப் பதிவு செய்"),
  "booked" to ("Booking exists" to "முன்பதிவு உள்ளது"),
  "not_booked" to ("No booking; payment resolved" to "முன்பதிவு இல்லை; கட்டண நிலை தீர்ந்தது"),
  "verified" to ("I checked official booking history and payment status; nothing is pending." to "அதிகாரப்பூர்வ முன்பதிவு வரலாறு மற்றும் கட்டண நிலையைச் சரிபார்த்தேன்; எதுவும் நிலுவையில் இல்லை."),
  "pnr" to ("PNR • 10 digits" to "PNR • 10 இலக்கங்கள்"),
  "allocation" to ("Coach / berth details (optional)" to "பெட்டி / படுக்கை விவரங்கள் (விருப்பம்)"),
  "status" to ("Ticket status" to "பயணச்சீட்டு நிலை"),
  "copy" to ("Copy" to "நகலெடு"),
  "copy_pnr" to ("Copy PNR" to "PNR நகலெடு"),
  "share" to ("Share trip details" to "பயண விவரங்களைப் பகிர்"),
  "copy_notice" to ("Copied for 60 seconds. Your keyboard or other apps may retain clipboard content." to "60 வினாடிகளுக்கு நகலெடுக்கப்பட்டது. விசைப்பலகை அல்லது பிற செயலிகள் நகலை வைத்திருக்கலாம்."),
  "cancel_record" to ("Mark cancelled after official cancellation" to "அதிகாரப்பூர்வ ரத்துக்குப் பின் ரத்தானதாகப் பதிவு செய்"),
  "cancel_confirm" to ("I cancelled this ticket on IRCTC. This action only updates my local record." to "IRCTC-இல் இந்தச் சீட்டை ரத்து செய்தேன். இந்தச் செயல் உள்ளூர் பதிவை மட்டுமே மாற்றும்."),
  "language" to ("Language" to "மொழி"),
  "theme" to ("Appearance" to "தோற்றம்"),
  "lock" to ("Require device unlock" to "சாதனத் திறத்தல் தேவை"),
  "privacy" to ("Privacy & security" to "தனியுரிமை & பாதுகாப்பு"),
  "privacy_body" to ("Passenger, journey and booking data are encrypted on this device using Android Keystore. No analytics, ads, passwords, OTP storage or server sync. Device backups are disabled. Uninstalling removes local records. IRCTC and your browser have their own privacy policies." to "பயணி, பயணம் மற்றும் முன்பதிவு விவரங்கள் Android Keystore மூலம் இந்தச் சாதனத்தில் மறையாக்கப்படுகின்றன. பகுப்பாய்வு, விளம்பரம், கடவுச்சொல், OTP சேமிப்பு அல்லது சர்வர் ஒத்திசைவு இல்லை. சாதனக் காப்புப்பிரதி முடக்கப்பட்டுள்ளது. செயலியை நீக்கினால் பதிவுகள் அழியும். IRCTC மற்றும் உலாவிக்குத் தனித் தனியுரிமைக் கொள்கைகள் உள்ளன."),
  "payment_note" to ("Preference only. Choose the available method and authorize payment on IRCTC. No payment secrets are saved." to "இது விருப்பம் மட்டுமே. கிடைக்கும் முறையைத் தேர்ந்து IRCTC-இல் பணம் செலுத்தவும். கட்டண ரகசியங்கள் சேமிக்கப்படாது."),
  "unlock" to ("Unlock saved details" to "சேமித்த விவரங்களைத் திற"),
  "locked" to ("Your details are locked" to "உங்கள் விவரங்கள் பூட்டப்பட்டுள்ளன"),
  "lock_setup" to ("Set a screen lock or biometric in Android Settings, then return." to "Android அமைப்புகளில் திரைப் பூட்டு அல்லது கைரேகை அமைத்துத் திரும்பவும்."),
  "open_settings" to ("Open security settings" to "பாதுகாப்பு அமைப்புகளைத் திற"),
  "loading" to ("Loading securely…" to "பாதுகாப்பாக ஏற்றுகிறது…"),
  "done" to ("Done" to "முடிந்தது"),
  "error" to ("Unable to continue" to "தொடர முடியவில்லை"),
  "storage_error" to ("Could not read or save securely. Your existing data was not reset. Try again; do not uninstall if a payment is pending." to "பாதுகாப்பாகப் படிக்க அல்லது சேமிக்க முடியவில்லை. பழைய தரவு அழிக்கப்படவில்லை. மீண்டும் முயலவும்; கட்டணம் நிலுவையில் இருந்தால் செயலியை நீக்காதீர்கள்."),
  "browser_error" to ("No browser could open IRCTC. Install or enable a trusted browser. The attempt remains locked until you resolve it." to "IRCTC திறக்க உலாவி இல்லை. நம்பகமான உலாவியை நிறுவவும். முடிவைப் பதிவு செய்யும்வரை முயற்சி பூட்டப்பட்டிருக்கும்."),
  "invalid_name" to ("Enter a valid passenger name (2–60 letters)." to "சரியான பயணிப் பெயரை உள்ளிடவும் (2–60 எழுத்துகள்)."),
  "invalid_age" to ("Age must be between 0 and 125." to "வயது 0 முதல் 125 வரை இருக்க வேண்டும்."),
  "invalid_nationality" to ("Use a two-letter nationality code." to "இரண்டு எழுத்துக் குடியுரிமைக் குறியீட்டைப் பயன்படுத்தவும்."),
  "invalid_group" to ("Enter a group name (up to 40 characters)." to "குழுப் பெயரை உள்ளிடவும் (40 எழுத்துகள் வரை)."),
  "invalid_child" to ("Child berth setting applies only below age 12." to "குழந்தைப் படுக்கை அமைப்பு 12 வயதிற்குக் கீழ் மட்டும்."),
  "invalid_stations" to ("Enter different valid station codes (2–5 letters)." to "வெவ்வேறு சரியான நிலையக் குறியீடுகளை உள்ளிடவும் (2–5 எழுத்துகள்)."),
  "invalid_boarding" to ("Enter the boarding station code." to "ஏறும் நிலையக் குறியீட்டை உள்ளிடவும்."),
  "invalid_date" to ("Enter today or a future boarding date as YYYY-MM-DD." to "இன்றைய அல்லது எதிர்கால ஏறும் தேதியை YYYY-MM-DD என உள்ளிடவும்."),
  "invalid_origin" to ("Check the train origin date: no later than boarding and within 7 days before it." to "முதல் நிலையத் தேதியைச் சரிபார்க்கவும்: ஏறும் தேதிக்கு முன் 7 நாட்களுக்குள் இருக்க வேண்டும்."),
  "invalid_train" to ("Enter the five-digit train number." to "ஐந்து இலக்க ரயில் எண்ணை உள்ளிடவும்."),
  "invalid_mobile" to ("Enter a valid 10-digit Indian mobile number." to "சரியான 10 இலக்க இந்திய கைப்பேசி எண்ணை உள்ளிடவும்."),
  "invalid_class" to ("1A is not supported for Tatkal. Choose General or another class." to "1A-க்கு தட்கல் ஆதரவு இல்லை. பொது ஒதுக்கீடு அல்லது மற்ற வகுப்பைத் தேர்வு செய்யவும்."),
  "invalid_passengers" to ("Select valid passengers: up to 4 for Tatkal, 6 for General. Check children and eligibility on IRCTC." to "சரியான பயணிகளைத் தேர்வு செய்: தட்கல் 4 வரை; பொது 6 வரை. குழந்தைகள் மற்றும் தகுதியை IRCTC-இல் சரிபார்."),
  "unresolved_attempt" to ("Resolve the previous booking attempt first." to "முந்தைய முன்பதிவு முயற்சியின் முடிவை முதலில் பதிவு செய்."),
  "verify_history" to ("Verify official booking history and payment status first." to "முதலில் அதிகாரப்பூர்வ முன்பதிவு வரலாறு மற்றும் கட்டண நிலையைச் சரிபார்."),
  "invalid_pnr" to ("PNR must contain 10 digits." to "PNR 10 இலக்கங்களைக் கொண்டிருக்க வேண்டும்."),
  "invalid_transition" to ("This step cannot be advanced. Verify the outcome on IRCTC." to "இந்தப் படிநிலையைத் தொடர முடியாது. IRCTC-இல் முடிவைச் சரிபார்."),
  "SYSTEM" to ("System" to "சாதன அமைப்பு"),
  "LIGHT" to ("Light" to "ஒளி"),
  "DARK" to ("Dark" to "இருள்"),
  "TATKAL" to ("Tatkal" to "தட்கல்"),
  "PREMIUM_TATKAL" to ("Premium Tatkal" to "பிரீமியம் தட்கல்"),
  "GENERAL" to ("General" to "பொது"),
  "MALE" to ("Male" to "ஆண்"),
  "FEMALE" to ("Female" to "பெண்"),
  "TRANSGENDER" to ("Transgender" to "திருநர்"),
  "NO_PREFERENCE" to ("No preference" to "விருப்பம் இல்லை"),
  "LOWER" to ("Lower" to "கீழ்"),
  "MIDDLE" to ("Middle" to "நடு"),
  "UPPER" to ("Upper" to "மேல்"),
  "SIDE_LOWER" to ("Side lower" to "பக்கவாட்டு கீழ்"),
  "SIDE_UPPER" to ("Side upper" to "பக்கவாட்டு மேல்"),
  "VEG" to ("Vegetarian" to "சைவம்"),
  "NON_VEG" to ("Non-vegetarian" to "அசைவம்"),
  "IRCTC_EWALLET" to ("IRCTC eWallet" to "IRCTC இ-வாலட்"),
  "UPI" to ("UPI" to "UPI"),
  "NET_BANKING" to ("Net banking" to "இணைய வங்கி"),
  "CARD" to ("Card" to "அட்டை"),
  "OTHER" to ("Other" to "மற்றவை"),
  "PREPARED" to ("Prepared" to "தயார்"),
  "LOGIN_REQUIRED" to ("Login required" to "உள்நுழைய வேண்டும்"),
  "TRAIN_SELECTION" to ("Train selection" to "ரயில் தேர்வு"),
  "PASSENGER_DETAILS" to ("Passenger details" to "பயணிகள் விவரம்"),
  "CAPTCHA_REQUIRED" to ("CAPTCHA / OTP input" to "CAPTCHA / OTP உள்ளீடு"),
  "REVIEW" to ("Review" to "சரிபார்ப்பு"),
  "PAYMENT" to ("Payment" to "கட்டணம்"),
  "PAYMENT_PENDING" to ("Payment pending" to "கட்டணம் நிலுவை"),
  "BOOKED" to ("Booked" to "முன்பதிவானது"),
  "FAILED" to ("Not booked" to "முன்பதிவாகவில்லை"),
  "UNKNOWN" to ("Status unknown" to "நிலை தெரியவில்லை"),
  "CONFIRMED" to ("Confirmed" to "உறுதிசெய்யப்பட்டது"),
  "RAC" to ("RAC" to "RAC"),
  "WAITLIST" to ("Waitlist" to "காத்திருப்புப் பட்டியல்"),
  "CANCELLED" to ("Cancelled" to "ரத்தானது"),
 ) }
}